config/routes.rb
Invoicer::Application.routes.draw do

  resources :expenses do
    member do
      get 'file'
    end
  end

  get 'invoice_items' => 'invoice_items#index'
  resources :tax_rates
  resources :invoices do
    collection do
      get 'reports'
    end
  end
  resources :invoice_statuses
  resources :clients do
    resources :addresses
  end
  devise_for :users
  resources :users do
    resources :addresses, controller: 'user_addresses'
  end
  match '/balance' => 'dashboard#balance', as: :balance, via: [:get, :post]
  root to: "dashboard#index"

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :invoices, :dependent => :restrict_with_error
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :addresses, dependent: :destroy
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  has_attached_file :file, :path => ":rails_root/system/:attachment/:id/:filename"
  do_not_validate_attachment_file_type :file

  default_scope { order('"date" desc') }
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :invoice_status
  has_many :invoice_items, dependent: :destroy
  validates_presence_of :client_id, :date, :due_date, :invoice_number, :user_address, :invoice_status
  accepts_nested_attributes_for :invoice_items, allow_destroy: true
  after_initialize :set_invoice_number
  belongs_to :user_address, class_name: Address, foreign_key: :address_id
  default_scope { order('"date" desc') }

  before_save :set_total

  def set_invoice_number
    return unless self.new_record?
    prev = Invoice.order('created_at desc').first
    if prev.nil?
      self.invoice_number ||= 1
    else
      self.invoice_number = prev.invoice_number.gsub(/\d+/){|m| m.to_i+1}
    end
  end

  def set_total
    total = 0
    invoice_items.to_a.each do |item|
      total += item.price * item.quantity
    end
    self.total = total
  end
end

app/models/invoice_item.rb
class InvoiceItem < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :tax_rate
end

app/models/invoice_status.rb
class InvoiceStatus < ActiveRecord::Base
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses, dependent: :destroy
  has_one :default_address, -> { where(default: true) }, class_name: Address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  inherit_resources
  belongs_to :client

  def permitted_params
    params.permit(:address => [:business_name, :address, :address2, :city, :county, :postcode, :country, :postcode, :phone, :email, :website, :email, :bank_details, :default])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  respond_to :html
  respond_to :json, only: :index
  inherit_resources

  def index
    super do
      @clients = @clients.where("name like ?", "%#{params[:q]}%")
    end
  end

  def create
    create! { client_addresses_path(@client) }
  end

  def permitted_params
    params.permit(:client => [:name, :address, :address2, :city, :county, :postcode, :country, :tax_number, :phone, :email, :website])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def balance
    @q = Invoice.unscoped.search(params[:q])
    @invoices = @q.result(distinct: true)
    @q2 = Expense.unscoped.search(params[:q])
    @expenses = @q2.result(distinct: true)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  inherit_resources

  def file
    @expense = Expense.find(params[:id])
   send_file @expense.file.path, :type => @expense.file_content_type
  end

  private
  def permitted_params
    params.permit(expense: [:name, :date, :amount, :file, :note])
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  inherit_resources
  respond_to :pdf, only: :show

  def reports
    @q = Invoice.unscoped.search(params[:q])
    @invoices = @q.result(distinct: true)
  end

  def new
    @invoice = Invoice.new
    super
  end

  def create
    @invoice = Invoice.new(permitted_params)
    @invoice.user_address = current_user.default_address
    create!
  end

  def update
    @invoice = Invoice.find(params[:id])
    @invoice.update(permitted_params)
    redirect_to @invoice
  end

  def show
    super do |format|
      @address = []
      [:address, :address2, :city, :county, :country, :postcode, :phone, :fax, :mobile, :website].each do |field|
        value = @invoice.user_address.send(field)
        @address<< value unless value.blank?
      end
      @bill_to = []
      [:name, :address, :address2, :city, :county, :country, :postcode].each do |field|
        value = @invoice.send(field)
        @bill_to<< value unless value.blank?
      end
      format.pdf { render pdf: "invoice##{@invoice.invoice_number}", layout: 'pdf.html' }
    end
  end

  private
    def permitted_params
      params.require(:invoice).permit([:date, :client_id, :invoice_number, :due_date ,:name ,:address ,:address2 ,:city ,:county, :postcode ,:country ,:tax_number, :invoice_status_id, :invoice_items_attributes => [:name, :description, :tax_rate_id, :quantity, :unit, :price, :_destroy, :id], :invoice_items => [:id, :name, :description, :tax_rate_id, :quantity, :unit, :price, :_destroy]])
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  def permitted_params
    params.permit(:user => [:email, :password, :password_confirmation])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-mini", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/helpers/invoice_statuses_helper.rb
module InvoiceStatusesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/tax_rates_helper.rb
module TaxRatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td>
          <%= link_to 'Addresses', client_addresses_path(client), class: 'btn btn-small' %>
          <%= link_to 'Show', client, class: 'btn btn-small' %>
          <%= link_to 'Edit', edit_client_path(client), class: 'btn btn-small' %>
          <%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path, class: 'btn btn-small btn-primary' %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice, html: {class: 'form-inline'}) do |f| %>
  <%= f.error_notification %>

  <div>
    <fieldset>
      <div class="row">
        <div class="span3">
          <%= f.input :invoice_number %>
        </div>
        <div class="span3">
          <%= f.association :invoice_status, label: 'Status' %>
        </div>
        <div class="span3">
          <%= f.input :date, as: :string, input_html: { data: {behaviour: "datepicker"} } %>
        </div>
        <div class="span3">
          <%= f.input :due_date, as: :string, input_html: { data: {behaviour: "datepicker"} } %>
        </div>
      </div>
    </fieldset>
    <fieldset>
      <legend>Client details</legend>
      <%= f.input :name, as: :string %>
      <div>
        <%= f.input :client_id, as: :hidden %>
      </div>
      <div class="row">
        <div class="span3">
          <%= f.input :city %>
        </div>
        <div class="span3">
          <%= f.input :address %>
        </div>
        <div class="span6">
          <%= f.input :address2 %>
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <%= f.input :county %>
        </div>
        <div class="span3">
          <%= f.input :postcode %>
        </div>
        <div class="span3">
          <%= f.input :country, as: :string %>
        </div>
        <div class="span3">
          <%= f.input :tax_number %>
        </div>
      </div>
    </fieldset>
  </div>

  <fieldset class="form-inline">
    <legend>Items</legend>
    <table class="table" id="items">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Tax rate</th>
          <th>Quantity</th>
          <th>Unit</th>
          <th>Price</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= f.simple_fields_for :invoice_items do |i| %>
          <%= render 'invoice_item_fields', f: i %>
        <% end %>
      </tbody>
    </table>
    <%= link_to_add_fields "Add item", f, :invoice_items %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </fieldset>
<% end %>

app/views/invoices/_invoice_item_fields.html.erb
<tr>
  <td>
    <%= f.text_field :name, placeholder: 'Name', class: 'input-small invoice-item-name' %>
  </td>
  <td class="span3">
    <%= f.text_field :description, placeholder: 'Description' %>
  </td>
  <td>
      <%= f.collection_select :tax_rate, TaxRate.all, :id, :name, {}, { class: 'input-small' } %>
  </td>
  <td>
      <%= f.text_field :quantity, placeholder: 'Quantity', class: 'input-small' %>
  </td>
  <td>
      <%= f.text_field :unit, placeholder: 'Unit', class: 'input-small' %>
  </td>
  <td>
      <%= f.text_field :price, placeholder: 'Price', class: 'input-small' %>
  </td>
  <td>
    <%= link_to "remove", '#', class: "remove_fields btn btn-mini btn-danger" %>
  </td>
</tr>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table class="table">
  <thead>
    <tr>
      <th>Invoice number</th>
      <th>Due date</th>
      <th>Client</th>
      <th>Invoice status</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_number %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.name %></td>
        <td><%= invoice.invoice_status.name %></td>
        <td><%= number_to_currency invoice.total %></td>
        <td>
          <%= link_to 'Show', invoice_path(invoice, format: :pdf), class: 'btn btn-small' %>
          <%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-small' %>
          <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Invoice', new_invoice_path, class: 'btn btn-small btn-primary' %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/reports.html.erb
<h1>Search</h1>
<%= search_form_for @q, url: reports_invoices_path do |f| %>
  <div class="row">
    <div class="span3">
      <%= f.label :date_gteq %>
      <%= f.text_field :date_gteq, { data: {behaviour: "datepicker"} } %>
    </div>
    <div class="span3">
      <%= f.label :date_lteq %>
      <%= f.text_field :date_lteq, { data: {behaviour: "datepicker"} } %>
    </div>
  </div>
  <%= f.submit 'Search', class: 'btn btn-primary' %>
<% end %>


<table class="table">
  <thead>
    <tr>
      <th>Invoice number</th>
      <th>Due date</th>
      <th>Client</th>
      <th>Invoice status</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_number %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.name %></td>
        <td><%= invoice.invoice_status.name %></td>
        <td><%= number_to_currency invoice.total %></td>
        <td>
          <%= link_to 'Show', invoice_path(invoice, format: :pdf), class: 'btn btn-small' %>
          <%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-small' %>
          <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
    <tr>
        <td colspan="4"></td>
        <td><%= number_to_currency @invoices.collect{|a| a.total}.sum %></td>
        <td>
        </td>
      </tr>
  </tbody>
</table>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% chart_data = @invoices.group_by_month(:date).sum(:total) %>
<%= line_chart chart_data %>

app/views/invoices/show.html.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <h1><%= @invoice.user_address.business_name %></h1>
      <%== @address.join('<br />') %>
      <br />
      <strong>Bank account:</strong><br />
      <%== @invoice.user_address.bank_details.gsub("\n", "<br />") %>
      </p>
    </div>
    <div class="span3 offset3">
      <h1>Invoice <%= @invoice.invoice_number %></h1>
    </div>
  </div>
  <div class="row" id="bill-to">
    <div class="span6">
      <strong>Bill to:</strong><br />
      <%== @bill_to.join('<br />') %>
    </div>
    <div class="span3 offset3">
      <table>
        <tr>
          <td><strong>Invoice Date:</strong></td>
          <td align="right"><%= @invoice.date %></td>
        </tr>
        <tr>
          <td><strong>Due Date:</strong></td>
          <td align="right"><%= @invoice.due_date %></td>
        </tr>
        <tr>
          <td><strong>Amount Due:</strong></td>
          <td align="right"><%= number_to_currency(@invoice.total) %></td>
        </tr>
      </table>
    </div>
  </div>
  <table class="table" id="items">
    <thead>
      <tr>
        <th>Item</th>
        <th>Description</th>
        <th>Qty</th>
        <th>Unit</th>
        <th>Price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @invoice.invoice_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
        <td><%= item.unit %></td>
        <td><%= number_to_currency(item.price) %></td>
        <td><%= number_to_currency(item.price * item.quantity) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="span4 offset8 text-right">
      <table class="table">
        <tr>
          <td>Total:</td>
          <td><%= number_to_currency @invoice.total %></td>
        </tr>
        <tr>
          <td>Balance:</td>
          <td><%= number_to_currency @invoice.total %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/invoices/show.pdf.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <h1><%= @invoice.user_address.business_name %></h1>
      <%== @address.join('<br />') %>
      <br />
      <strong>Bank account:</strong><br />
      <%== @invoice.user_address.bank_details.gsub("\n", "<br />") %>
      </p>
    </div>
    <div class="span3 offset3">
      <h1>Invoice <%= @invoice.invoice_number %></h1>
    </div>
  </div>
  <div class="row" id="bill-to">
    <div class="span6">
      <strong>Bill to:</strong><br />
      <%== @bill_to.join('<br />') %>
    </div>
    <div class="span3 offset3">
      <table>
        <tr>
          <td><strong>Invoice Date:</strong></td>
          <td align="right"><%= @invoice.date %></td>
        </tr>
        <tr>
          <td><strong>Due Date:</strong></td>
          <td align="right"><%= @invoice.due_date %></td>
        </tr>
        <tr>
          <td><strong>Amount Due:</strong></td>
          <td align="right"><%= number_to_currency(@invoice.total) %></td>
        </tr>
      </table>
    </div>
  </div>
  <table class="table" id="items">
    <thead>
      <tr>
        <th>Item</th>
        <th>Description</th>
        <th>Qty</th>
        <th>Unit</th>
        <th>Price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @invoice.invoice_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
        <td><%= item.unit %></td>
        <td><%= number_to_currency(item.price) %></td>
        <td><%= number_to_currency(item.price * item.quantity) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="span4 offset8 text-right">
      <table class="table">
        <tr>
          <td>Total:</td>
          <td><%= number_to_currency @invoice.total %></td>
        </tr>
        <tr>
          <td>Balance:</td>
          <td><%= number_to_currency @invoice.total %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, :required => true, :autofocus => true %>

    <%= f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false %>
    <%= f.input :password_confirmation, :required => false %>
    <%= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>