config/routes.rb
Invoicer::Application.routes.draw do

  resources :expenses do
    member do
      get 'file'
    end
  end

  get 'invoice_items' => 'invoice_items#index'
  resources :tax_rates
  resources :invoices do
    collection do
      get 'reports'
    end
  end
  resources :invoice_statuses
  resources :clients do
    resources :addresses
  end
  devise_for :users
  resources :users do
    resources :addresses, controller: 'user_addresses'
  end
  match '/balance' => 'dashboard#balance', as: :balance, via: [:get, :post]
  root to: "dashboard#index"

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :invoices, :dependent => :restrict_with_error
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :addresses, dependent: :destroy
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  has_attached_file :file, :path => ":rails_root/system/:attachment/:id/:filename"
  do_not_validate_attachment_file_type :file

  default_scope { order('"date" desc') }
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :invoice_status
  has_many :invoice_items, dependent: :destroy
  validates_presence_of :client_id, :date, :due_date, :invoice_number, :user_address, :invoice_status
  accepts_nested_attributes_for :invoice_items, allow_destroy: true
  after_initialize :set_invoice_number
  belongs_to :user_address, class_name: Address, foreign_key: :address_id
  default_scope { order('"date" desc') }

  before_save :set_total

  def set_invoice_number
    return unless self.new_record?
    prev = Invoice.order('created_at desc').first
    if prev.nil?
      self.invoice_number ||= 1
    else
      self.invoice_number = prev.invoice_number.gsub(/\d+/){|m| m.to_i+1}
    end
  end

  def set_total
    total = 0
    invoice_items.to_a.each do |item|
      total += item.price * item.quantity
    end
    self.total = total
  end
end

app/models/invoice_item.rb
class InvoiceItem < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :tax_rate
end

app/models/invoice_status.rb
class InvoiceStatus < ActiveRecord::Base
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses, dependent: :destroy
  has_one :default_address, -> { where(default: true) }, class_name: Address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  inherit_resources
  belongs_to :client

  def permitted_params
    params.permit(:address => [:business_name, :address, :address2, :city, :county, :postcode, :country, :postcode, :phone, :email, :website, :email, :bank_details, :default])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  respond_to :html
  respond_to :json, only: :index
  inherit_resources

  def index
    super do
      @clients = @clients.where("name like ?", "%#{params[:q]}%")
    end
  end

  def create
    create! { client_addresses_path(@client) }
  end

  def permitted_params
    params.permit(:client => [:name, :address, :address2, :city, :county, :postcode, :country, :tax_number, :phone, :email, :website])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  inherit_resources

  def file
    @expense = Expense.find(params[:id])
   send_file @expense.file.path, :type => @expense.file_content_type
  end

  private
  def permitted_params
    params.permit(expense: [:name, :date, :amount, :file, :note])
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  inherit_resources
  respond_to :pdf, only: :show

  def reports
    @q = Invoice.unscoped.search(params[:q])
    @invoices = @q.result(distinct: true)
  end

  def new
    @invoice = Invoice.new
    super
  end

  def create
    @invoice = Invoice.new(permitted_params)
    @invoice.user_address = current_user.default_address
    create!
  end

  def update
    @invoice = Invoice.find(params[:id])
    @invoice.update(permitted_params)
    redirect_to @invoice
  end

  def show
    super do |format|
      @address = []
      [:address, :address2, :city, :county, :country, :postcode, :phone, :fax, :mobile, :website].each do |field|
        value = @invoice.user_address.send(field)
        @address<< value unless value.blank?
      end
      @bill_to = []
      [:name, :address, :address2, :city, :county, :country, :postcode].each do |field|
        value = @invoice.send(field)
        @bill_to<< value unless value.blank?
      end
      format.pdf { render pdf: "invoice##{@invoice.invoice_number}", layout: 'pdf.html' }
    end
  end

  private
    def permitted_params
      params.require(:invoice).permit([:date, :client_id, :invoice_number, :due_date ,:name ,:address ,:address2 ,:city ,:county, :postcode ,:country ,:tax_number, :invoice_status_id, :invoice_items_attributes => [:name, :description, :tax_rate_id, :quantity, :unit, :price, :_destroy, :id], :invoice_items => [:id, :name, :description, :tax_rate_id, :quantity, :unit, :price, :_destroy]])
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  def permitted_params
    params.permit(:user => [:email, :password, :password_confirmation])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-mini", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/helpers/invoice_statuses_helper.rb
module InvoiceStatusesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/tax_rates_helper.rb
module TaxRatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= simple_form_for([parent, @address]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :default %>
    <%= f.input :business_name %>
    <%= f.input :address %>
    <%= f.input :address2 %>
    <%= f.input :city %>
    <%= f.input :county %>
    <%= f.input :country, as: :string %>
    <%= f.input :postcode %>
    <%= f.input :phone %>
    <%= f.input :fax %>
    <%= f.input :mobile %>
    <%= f.input :website %>
    <%= f.input :email %>
    <%= f.input :tax_number %>
    <%= f.input :bank_details %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'addresses/form' %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Business name</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>County</th>
      <th>Country</th>
      <th>Postcode</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.business_name %></td>
        <td><%= address.address %></td>
        <td><%= address.address2 %></td>
        <td><%= address.city %></td>
        <td><%= address.county %></td>
        <td><%= address.country %></td>
        <td><%= address.postcode %></td>
        <td>
          <%= link_to 'Show', resource_path(address), class: 'btn btn-small' %>
          <%= link_to 'Destroy', resource_path(address), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Address', new_resource_url, class: 'btn btn-small btn-primary' %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'addresses/form' %>

<%= link_to 'Back', resource_path(parent) %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business name:</strong>
  <%= @address.business_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @address.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @address.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>County:</strong>
  <%= @address.county %>
</p>

<p>
  <strong>Country:</strong>
  <%= @address.country %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @address.postcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @address.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @address.fax %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @address.mobile %>
</p>

<p>
  <strong>Website:</strong>
  <%= @address.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @address.email %>
</p>

<p>
  <strong>Bank details:</strong>
  <%= @address.bank_details %>
</p>

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense, multipart: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :date, as: :string, input_html: { data: {behaviour: "datepicker"}, value: @expense.date.to_s } %>
    <%= f.input :amount %>
    <%= f.input :note %>
    <%= f.input :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Amount</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.name %></td>
        <td><%= expense.date %></td>
        <td><%= expense.amount %></td>
        <td>
          <%= link_to 'Show', expense, class: 'btn btn-small' %>
          <%= link_to 'Edit', edit_expense_path(expense), class: 'btn btn-small' %>
          <%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path, class: 'btn btn-primary' %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>
<% unless @expense.file.nil? %>
<p>
  <strong>File:</strong>
  <%= link_to @expense.file_file_name, file_expense_path(@expense.id) %>
</p>
<% end %>
<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>